apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Chart.Name }}-sc-{{ .Release.Namespace }}-mongo
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-{{ .Release.Namespace }}-mongo
spec:
  capacity:
    storage: {{ .Values.StorageCapacity }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Chart.Name }}-sc-{{ .Release.Namespace }}-mongo
  nfs:
    path: {{ .Values.StoragePath }}/{{ .Chart.Name }}-mongo/db
    server: {{ .Values.StorageServer }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-mongo
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.StorageCapacity }}
  storageClassName: {{.Chart.Name }}-sc-{{ .Release.Namespace }}-mongo