apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-mongo-svc"
  labels:
    app: "{{ .Chart.Name }}-mongo-svc"
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ .Chart.Name }}-mongo-pod"
