apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-svc"
  labels:
    app: "{{ .Chart.Name }}-svc"
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ .Chart.Name }}-pod"
