apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-dep"
  labels:
    app: "{{ .Chart.Name }}-dep"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}-pod"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}-pod"
    spec:
      containers:
        - name: "{{ .Chart.Name }}-con"
          image: "{{ .Values.image.yapi }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: YAPI_ADMIN_ACCOUNT
              value: "admin@docker.yapi"
            - name: YAPI_ADMIN_PASSWORD
              value: "adm1n"
            - name: YAPI_CLOSEEGISTER
              value: true
            - name: YAPI_DB_SERVERNAME
              value: "{{ .Chart.Name }}-mongo-svc"
            - name: YAPI_DB_USER
              value: "admin"
            - name: YAPI_DB_PASS
              value: "secret123"
            - name: YAPI_DB_AUTH_SOURCE
              value: "admin"
            - name: YAPI_DB_PORT
              value: "27017"
            - name: YAPI_DB_DATABASE
              value: "yapi"
            - name: YAPI_MAIL_ENABLE
              value: false
            - name: YAPI_LDAP_LOGIN_ENABLE
              value: false
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
